- src/components.d.ts
- src/components/PageConnectInfoItems.vue
- src/store.ts
> feat(gocqhttp): 新增gocqhttp账号时，支持填写签名服务器信息

- src/App.vue
- src/components.d.ts
- src/store.ts
> feat(news): 海豹新闻增加红点提醒和已读

- src/components/PageConnectInfoItems.vue
> feat(gocqhttp): apad的内置gocqhttp也支持填写签名服务

- src/App.vue
- src/components/PageLog.vue
**Hover**
**<480px**
怕挡住 log 加了点透明度
> feat: webui 日志 回到底部 按钮 (#9)

- .github/workflows/build.yml
为了支持core自动下载打包ui资源文件，构建后自动发布pre-release
> ci: 自动发布pre-release版本

- src/components/PageTest.vue
> feat(testui): 测试界面增加牌堆/js/帮助文档的重载按钮

- src/components/misc/PageMiscSettings.vue
Issue 见 https://github.com/sealdice/sealdice-core/issues/126
> feat: 增加两个设置项，用于骰点上限和 COC 制卡上限

- src/App.vue
- src/components.d.ts
- src/components/PageMod.vue
- src/components/mod/PageCensor.vue
- src/components/mod/censor/CensorConfig.vue
- src/components/mod/censor/CensorFiles.vue
- src/components/mod/censor/CensorLog.vue
- src/components/mod/censor/CensorWords.vue
- src/components/mod/censor/censor.ts
> feat(censor): 敏感词ui部分

- src/components/mod/PageCensor.vue
- src/components/mod/censor/CensorConfig.vue
- src/components/mod/censor/CensorFiles.vue
- src/components/mod/censor/censor.ts
> fix(censor): 调整默认的拦截模式为仅回复，并调整部分提示信息

- src/components/misc/PageMiscSettings.vue
https://github.com/sealdice/sealdice-core/pull/268
> feat(Master设置): 修改Master列表设置的提示文案

- src/components/misc/PageMiscBanList.vue
- src/components/mod/censor/CensorConfig.vue
~~主要防止误解连带责任的值，造成连带责任为200倍的情况~~
> feat(ban): 调整黑白名单的设置项样式，控制数字值的输入范围

- package.json
- src/components/mod/PageJs.vue
- src/components/mod/PageMiscDeck.vue
- src/components/mod/diff-viewer.vue
- src/main.ts
- src/store.ts
> feat(deck): 增加牌堆远程更新按钮，并提供对比

- src/components/misc/PageMiscSettings.vue
- src/store.ts
> feat(mail): 支持发送测试邮件

- src/components/misc/PageMiscBackup.vue
- src/store.ts
依赖 sealdice/sealdice-core#291 提供的接口
> feat(backup): 增加备份批量删除功能

- src/components/misc/PageMiscBanList.vue
> feat(ban): 提供黑名单立即退群功能

- src/components/PageConnectInfoItems.vue
- src/store.ts
> feat(gocqhttp): 内置gocq支持切换协议版本

- src/components/misc/PageMiscBackup.vue
> feat(bak): 修复单个备份删除，同时调整批量删除样式

- src/components/PageCustomText.vue
- src/store.ts
> feat(custom-text): 自定义文案项展示相应的额外信息

- src/components/misc/PageMiscBanList.vue
- src/store.ts
> feat(ban): 调整黑白名单列表样式，增加导入导出功能按钮

- package.json
- src/components/PageCustomText.vue
- src/components/misc/PageMiscBackup.vue
- src/components/mod/PageJs.vue
sealdice/sealdice-core#336 对应的前端修改
ref sealdice/sealdice-core#327
close #70
> feat(backup): 自动备份清理-前端

- src/components/PageConnectInfoItems.vue
- src/store.ts
依赖后端 sealdice/sealdice-core#341
issue: sealdice/sealdice-core#332
> feat(red-protocol): red 协议的ui适配

- src/components/mod/PageJs.vue
- src/type.d.ts
> feat(js): 支持加载错误的js脚本在列表显示和管理

- src/components/PageConnectInfoItems.vue
- src/store.ts
后端部分: sealdice/sealdice-core#400
> feat: Slack Adapter 前端实现

- src/components/misc/PageMiscSettings.vue
https://github.com/sealdice/sealdice-core/pull/406
> feat: 群组刷屏警告

- src/components/PageConnectInfoItems.vue
- src/store.ts
https://github.com/sealdice/sealdice-core/pull/459 的ui部分
顺便修复了
[sealdice-core #381 ](https://github.com/sealdice/sealdice-core/issues/381)
> feat: 支持onebot v11 ws反向连接

- package.json
- src/components/misc/PageMiscGroup.vue
不过行为还没改，退群要改成什么呢？
https://github.com/sealdice/sealdice-core/issues/398
> imp: 优化了群组管理，提升速度，并支持更多平台

- src/components/PageConnectInfoItems.vue
- src/store.ts
此 https://github.com/sealdice/sealdice-core/pull/560 的前端部分
> fix(OfficialQQ): 不能“只在频道中使用”

- src/components/PageConnectInfoItems.vue
- src/store.ts
* fix(OfficialQQ): 不能“只在频道中使用”
https://github.com/sealdice/sealdice-core/issues/530
* type addImConnectionForm
---------
> fix(OfficialQQ): 不能“只在频道中使用” (#141)

- src/components/PageConnectInfoItems.vue
fix sealdice/sealdice-core#384
> fix: 修复“添加账号”按钮显示异常

- src/components/misc/PageMiscSettings.vue
Ref Issue sealdice/sealdice-core#568
Related PR sealdice/sealdice-core#581
> imp(Session): 自动退群新排期配置

- src/components/misc/PageMiscSettings.vue
Close sealdice/sealdice-core#592
> fix: 修复消息通知列表加号有时无效的bug

- src/components/misc/PageMiscSettings.vue
Close sealdice/sealdice-core#382
> imp(MiscSetting): 调整若干 tooltip 的位置

- src/store.ts
> fix: 修复 Helpdoc 无法上传的问题

- src/components/mod/PageStory.vue
Ref sealdice/sealdice-core#545
> feat(Story): 跑团日志分页查询修复

- src/App.vue
- src/store.ts
> feat: 版本展示适配新的版本号格式

- src/components.d.ts
- src/components/mod/PageStory.vue
- src/components/mod/story/StoryBackup.vue
- src/components/mod/story/story.ts
> feat(story): 跑团日志页面增加跑团日志备份文件管理 tab

- src/App.vue
- src/components.d.ts
- src/components/PageMisc.vue
- src/components/misc/PageMiscAdvancedSettings.vue
- src/store.ts
- src/type.d.ts
> feat(storylog): 增加高级设置，支持设置自定义跑团日志后端

- src/components/PageConnectInfoItems.vue
- src/store.ts
> imp: ob11的正向连接在用户忘记添加的协议前缀的情况下，自动添加ws://前缀

- src/components/PageConnectInfoItems.vue
- src/store.ts
Ref: sealdice/sealdice-core#709
> feat: LagrangeGo 前端实现

- src/components/PageConnectInfoItems.vue
- src/store.ts
Ref: sealdice/sealdice-core#724
> feat(LagrangeGo): custom sign frontend

- src/components/mod/PageJs.vue
- src/type.d.ts
> feat: 插件配置项简介

- src/components/mod/PageMiscDeck.vue
> feat(Deck): 加载错误的牌堆展示错误提示

- src/components/PageLog.vue
> feat(Logs): 调整日志样式，使出错日志更醒目

- src/components/mod/PageJs.vue
> feat(JS): 调整 js 插件设置样式

- src/components.d.ts
- src/components/mod/PageCustomReply.vue
- src/components/tools/custom-reply-condition.vue
- src/components/tools/foldable-card.vue
- src/components/tools/nested.vue
Ref sealdice/sealdice-core#755
> feat(CustomReply): 自定义回复支持文件级公共执行条件

- src/App.vue
- src/components/PageMisc.vue
- src/components/misc/PageMiscAdvancedSettings.vue
- src/type.d.ts
> feat(AdvancedSetting): 高级设置页可以控制菜单的显隐与是否启用

- src/components/mod/PageJs.vue
- src/type.d.ts
关联后端PR：https://github.com/sealdice/sealdice-core/pull/802
没写过 Vue，模仿上下文写的（x 请仔细检查
> feat(js): 实现插件配置项有序展示，并优先展示 description

- src/components/tool/PageTest.vue
- src/store.ts
> feat(Test): 指令测试页增加私聊/群聊模式切换

- package-lock.json
- package.json
- src/components.d.ts
- src/components/mod/PageStory.vue
Resolved sealdice/sealdice-core#624
> feat(Story): 跑团日志预览颜色生成调整

- src/components/mod/PageStory.vue
先使用挑选的色板，用完了再按色系生成随机深色
Resolved sealdice/sealdice-core#624
> feat(Story): 进一步改进跑团日志预览的颜色生成

- src/components/mod/PageCustomReply.vue
- src/components/utils/custom-reply-condition.vue
- src/components/utils/foldable-card.vue
- src/components/utils/nested.vue
Fix sealdice/sealdice-core#809
> fix(CustomReply): 修复自定义回复项的拖动，调整样式以去除折叠变化时提示保存

- src/components/misc/PageMiscBackup.vue
- src/store.ts
对应后端调整：sealdice/sealdice-core#813
Ref sealdice/sealdice-core#758
> feat(Backup): 备份支持选择备份范围

- index.html
- src/components/PageLog.vue
- src/router/index.ts
- 修复访问远程服务器UI页面刷新报错
- 修复日志页跳转底部按钮时效
> fix(router): 修复切换为路由后的一些问题

- src/components/tool/PageResource.vue
> feat(Resource): 资源列表增加「复制海豹码」按钮

- package-lock.json
- package.json
- src/components/mod/PageJs.vue
- src/store/index.ts
后端 PR: https://github.com/sealdice/sealdice-core/pull/844
<details><summary>效果</summary>
</details>
> feat (JS): 为插件提供定时任务 API

- src/store/index.ts
fix [#882](https://github.com/sealdice/sealdice-core/issues/882)
> fix: function helpDocUpload() using wrong Content-Type

- package-lock.json
- package.json
- postcss.config.mjs
- src/components/Menu.vue
- src/components/PageAbout.vue
- src/components/PageLog.vue
- src/components/customText/CustomTextBox.vue
- src/components/misc/PageMiscAdvancedSettings.vue
- src/components/misc/PageMiscBackup.vue
- src/components/misc/PageMiscBanList.vue
- src/components/misc/PageMiscGroup.vue
- src/components/misc/PageMiscSettings.vue
- src/components/mod/PageCustomReply.vue
- src/components/mod/PageHelpDoc.vue
- src/components/mod/PageJs.vue
- src/components/mod/PageMiscDeck.vue
- src/components/mod/PageStory.vue
- src/components/mod/censor/CensorLog.vue
- src/components/mod/story/StoryBackup.vue
- src/components/tool/PageResource.vue
- src/components/tool/PageTest.vue
- src/components/utils/custom-reply-condition.vue
- src/components/utils/foldable-card.vue
- src/components/utils/nested.vue
- src/components/utils/resource-render.vue
- src/main.ts
- src/styles/index.scss
- vite.config.ts
Reverts sealdice/sealdice-ui#216
> Revert "imp: 使用 postcss 相关功能代替 scss 以提升编译速度"

- src/components/PageHome.vue
> feat(Log): 日志列表增加下拉查看最新提示

- src/components/PageConnectInfoItems.vue
- src/components/PageHome.vue
- src/store/index.ts
> feat(Lagrange): 支持设置内置拉格兰的签名版本

- components.d.ts
- src/components/utils/custom-reply-conditions.vue
- src/components/utils/nested.vue
Resolved sealdice/sealdice-core#990
> fix(custom-reply): 修复自定义回复删除条件按钮，删除条目后错误展示的问题

- src/components/mod/PageJs.vue
对应 Core 调整：sealdice/sealdice-core#1030
> feat(JS): 直接支持 typescript 扩展

- .env.development
- src/api/resource/index.ts
- src/components/mod/PageJs.vue
> Fix(api): 修复因修改ui api导致的功能失效

- src/api/im_connections/index.ts
- src/components/PageConnectInfoItems.vue
后端实现: https://github.com/sealdice/sealdice-core/pull/1164
> feat(Lagrange): 签名新版本的前端实现

- src/components/PageConnectInfoItems.vue
> fix(ui): 修复自定义签名表单的错误显示

- src/components/misc/banList/BanConfig.vue
- src/type.d.ts
前端部分，经过了测试，正常运行，但是不确定会不会引起其它地方什么连锁反应……
> feat: 添加"使用者为管理员立即退群，为普通群员仅拒绝回复"选项

- src/api/js/index.ts
- src/components/mod/PageJs.vue
后端 PR：https://github.com/sealdice/sealdice-core/pull/1220
> feat: 修改 delete_unused_config 为 delete_unused_configs，允许批量删除配置项

- src/api/im_connections/index.ts
- src/components/PageConnectInfoItems.vue
- src/store/index.ts
close https://github.com/sealdice/sealdice-core/issues/1232
测试预览如下，works on My machine
> fix:移除在线时长

- src/components/mod/PageCustomReply.vue
close https://github.com/sealdice/sealdice-core/issues/1456
> feat: 上传新自定义回复文件时 自动切换到新自定义回复文件
